'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, BriefcaseBusiness, CheckCircle2, Clock3, Compass, Filter, Search, TrendingUp, UsersRound, type LucideIcon } from 'lucide-react';
import { useAuthContext } from '@/components/providers/AuthProvider';
import { getJobs, getMatchesForEmployer, getMatchesForShelter, getResidents } from '@/lib/db';
import type { Job, JobMatch, Resident } from '@/types';

type Data={residents:Resident[];jobs:Job[];matches:JobMatch[]};
export function DashboardOverview({role}:{role:'shelter'|'employer'}){
  const {org}=useAuthContext();const[data,setData]=useState<Data|null>(null);const[error,setError]=useState('');
  useEffect(()=>{(async()=>{try{if(role==='shelter'){const sid=org.shelter?.id??'';const[residents,jobs,matches]=await Promise.all([getResidents(sid),getJobs(),getMatchesForShelter(sid)]);setData({residents,jobs,matches})}else{const eid=org.employer?.id??'';const[jobs,matches]=await Promise.all([getJobs(eid),getMatchesForEmployer(eid)]);setData({residents:[],jobs,matches})}}catch{setError('ไม่สามารถโหลดข้อมูลได้ โปรดลองอีกครั้ง')}})()},[role,org]);
  const title=role==='shelter'?org.shelter?.name:org.employer?.businessName;
  const stats:Array<[string,number|undefined,LucideIcon,string,string]>=role==='shelter'?[['งานที่ต้องโฟกัส',data?.matches.filter(x=>x.status==='suggested'||x.status==='worker_accepted').length,Clock3,'bg-brand-100 text-brand-700','รายการ'],['ผู้เข้าร่วมที่ดูแล',data?.residents.length,UsersRound,'bg-opportunity-100 text-opportunity-700','คน'],['อนุมัติแล้ว',data?.matches.filter(x=>x.status==='shelter_approved').length,CheckCircle2,'bg-hope-100 text-hope-700','คน']]:[['ประกาศงานที่เปิดอยู่',data?.jobs.filter(x=>x.status==='open').length,BriefcaseBusiness,'bg-brand-100 text-brand-700','ตำแหน่ง'],['ข้อเสนอที่กำลังดำเนินการ',data?.matches.filter(x=>x.status==='suggested'||x.status==='worker_accepted').length,Clock3,'bg-opportunity-100 text-opportunity-700','คน'],['อนุมัติแล้ว',data?.matches.filter(x=>x.status==='shelter_approved').length,CheckCircle2,'bg-hope-100 text-hope-700','คน']];
  return <div className="page-enter"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="font-bold text-brand-600">{title??(role==='shelter'?'ศูนย์พักพิง':'ผู้จ้างงาน')}</p><h1 className="mt-1 text-3xl font-extrabold text-slate-950">ภาพรวมงานของคุณ</h1><p className="mt-2 text-slate-600">ยินดีต้อนรับกลับ นี่คือสิ่งสำคัญสำหรับวันนี้</p></div><Link href={role==='shelter'?'/shelter/residents':'/employer/create-job'} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-[12px] bg-brand-600 px-5 font-bold text-white shadow-[0_3px_6px_oklch(55%_0.2_260_/_0.2)] hover:bg-brand-700">{role==='shelter'?'เพิ่มผู้เข้าร่วม':'ประกาศงานใหม่'} <ArrowRight size={17}/></Link></div>
    {error&&<p role="alert" className="mt-6 rounded-[12px] bg-red-50 p-4 font-semibold text-red-800">{error}</p>}
    <section aria-label="สรุปข้อมูล" className="mt-7 grid gap-4 md:grid-cols-3">{stats.map(([label,value,Icon,color,unit],index)=><div key={label} className={`lift rounded-[16px] bg-white p-5 shadow-[0_3px_8px_oklch(21%_0.025_255_/_0.07)] ${index===1?'md:translate-y-2':''}`}><div className="flex items-center justify-between"><span className={`grid h-11 w-11 place-items-center rounded-[13px] ${color}`}><Icon size={21}/></span>{index===2&&<span className="inline-flex items-center gap-1 text-sm font-bold text-hope-700"><TrendingUp size={15}/>ดีขึ้น</span>}</div>{data?<p className="mt-5 text-3xl font-extrabold tabular-nums text-slate-950">{value} <span className="text-base font-medium text-slate-500">{unit}</span></p>:<div className="mt-5 h-9 w-24 animate-pulse rounded bg-slate-100"/>}<p className="mt-1 font-semibold text-slate-700">{label}</p></div>)}</section>
    <section className="mt-8 flex flex-col justify-between gap-5 rounded-[16px] bg-gradient-to-r from-brand-50 via-sky-50 to-opportunity-50 p-5 ring-1 ring-brand-100 sm:flex-row sm:items-center sm:p-6"><div className="flex gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-brand-600 text-white"><Compass/></span><div><h2 className="text-lg font-bold text-slate-950">เริ่มต้นวันอย่างมั่นใจ</h2><p className="mt-1 max-w-2xl text-sm text-slate-600">ตรวจสิ่งที่ต้องทำก่อน แล้วติดตามความคืบหน้าของผู้เข้าร่วมจากพื้นที่เดียว</p></div></div><Link href={role==='shelter'?'/shelter/matching':'/employer/matches'} className="inline-flex min-h-11 shrink-0 items-center justify-center gap-2 rounded-[12px] bg-white px-4 font-bold text-brand-700 shadow-sm">ดูงานที่ต้องทำ <ArrowRight size={17}/></Link></section>
    <section className="mt-8 overflow-hidden rounded-[16px] bg-white shadow-[0_3px_8px_oklch(21%_0.025_255_/_0.07)]"><div className="flex flex-col justify-between gap-4 border-b border-slate-100 p-5 sm:flex-row sm:items-center"><div><h2 className="text-xl font-bold text-slate-950">งานที่ต้องติดตาม</h2><p className="text-sm text-slate-500">เรียงจากรายการที่ต้องตัดสินใจก่อน</p></div><div className="flex gap-2"><button className="grid h-11 w-11 place-items-center rounded-[11px] border border-slate-200 text-slate-600 hover:bg-slate-50" aria-label="ค้นหา"><Search size={18}/></button><button className="inline-flex min-h-11 items-center gap-2 rounded-[11px] border border-slate-200 px-3 text-sm font-bold text-slate-700 hover:bg-slate-50"><Filter size={17}/>ตัวกรอง</button></div></div>
      {!data?<div className="space-y-3 p-5">{[1,2,3].map(x=><div key={x} className="h-16 animate-pulse rounded-[12px] bg-slate-100"/>)}</div>:data.matches.length===0?<div className="p-10 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-brand-50 text-brand-600"><CheckCircle2/></span><h3 className="mt-4 font-bold text-slate-950">ทุกอย่างเรียบร้อยดี</h3><p className="mt-1 text-sm text-slate-600">รายการใหม่จะแสดงที่นี่พร้อมขั้นตอนถัดไป</p></div>:<div className="divide-y divide-slate-100">{data.matches.slice(0,5).map(match=><div key={match.id} className="grid gap-4 px-5 py-4 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><p className="font-bold text-slate-900">การจับคู่ #{match.id.slice(-4)}</p><p className="text-sm text-slate-500">อัปเดตล่าสุดวันนี้</p></div><div className="min-w-36"><div className="flex justify-between text-xs font-semibold text-slate-600"><span>ความเหมาะสม</span><span>{match.score}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-opportunity-600" style={{width:`${match.score}%`}}/></div></div><span className={`w-fit rounded-full px-3 py-1 text-sm font-bold ${match.status==='shelter_approved'?'bg-hope-100 text-hope-700':match.status==='worker_declined'||match.status==='shelter_declined'?'bg-red-100 text-red-700':'bg-brand-50 text-brand-700'}`}>{match.status==='shelter_approved'?'อนุมัติแล้ว':match.status==='worker_declined'||match.status==='shelter_declined'?'ไม่ดำเนินการต่อ':match.status==='worker_accepted'?'รอบ้านใหม่อนุมัติ':'รอผู้เข้าร่วม'}</span></div>)}</div>}
    </section>
  </div>
}
